keys:
  - &gear age1x7jy46z9yq5lrgpsmkmppp2x3m4pjutfgfxk552yq38st8u0lg4qemajc8
  - &zen age1ll97gtxezzc7fhq8g4qg3ny0xfxfd96rs3605d3ncrjvquhg4e6sscs27u
creation_rules:
  - path_regex: secrets/*
    key_groups:
    - age:
      - *gear
      - *zen
